config/routes.rb
Rails.application.routes.draw do
  get 'bill_imports/new'

  resources :bill_imports
  resources :bills do
    collection do
      post :import
    end
  end

  resources :searches
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'welcome/index'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }
  authenticated :user do
    root :to => 'bills#index', as: :authenticated_root
  end

  root :to => 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
require 'csv'


class Bill < ApplicationRecord
  belongs_to :user
  
  




validates_uniqueness_of :dvno, :scope => :month

  validates :section, :month, :typebill, :compactor, :rock, :shelf, :bundleno,  :presence => true

  validates_uniqueness_of :dvno, :scope => :month
  
  validates_numericality_of :dvno, :only_integer => true, :allow_nil => true, 
    :greater_than_or_equal_to => 1,
    :less_than_or_equal_to => 9999,
    :message => "can only be whole number between 1 and 9999."
  

validates_numericality_of :bundleno, :only_integer => true, :allow_nil => true, 
    :greater_than_or_equal_to => 1,
    :less_than_or_equal_to => 99,
    :message => "can only be whole number between 1 and 99."



   def self.search(search)
		if search
			where(["dvno LIKE ?", "%#{search}%"])
      
		else
			all
		end
	end

  def self.to_csv(options = {})
    desired_columns = ["id", "section", "year", "month", "dvno", "typebill", "compactor", "rock", "shelf", "bundleno"]
    CSV.generate(options) do |csv|
      csv << desired_columns
      all.each do |bill|
        csv << bill.attributes.values_at(*desired_columns)
      end
    end
  end
  
  def self.import(file)
    spreadsheet = Roo::Spreadsheet.open(file.path)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      bill = find_by(id: row["id"]) || new
      bill.attributes = row.to_hash
      bill.save!
    end
  end  

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
  
   skip_authorize_resource :only => [:show, :create]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.accessible_by(current_ability).paginate(:page => params[:page]).order('user_id').per_page(10).order(created_at: :desc).search(params[:search])#all
   
   respond_to do |format|
      format.html
      format.csv { send_data @bills.to_csv }

     end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  def import
    Bill.import(params[:file])
    
    redirect_to root_url, notice: 'Uploaded Bills Was Successfully imported.'
  end

  # GET /bills/new
  def new
    @bill = Bill.new
    #0.times { @bill.dvs.build}
  end

  # GET /bills/1/edit
  def edit
  end


  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)
     @bill.user_id = current_user.id

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:section, :year, :month, :dvno, :typebill, :compactor, :rock, :shelf, :bundleno, :section_id, :typebill_id, :user_id) #dvs_attributes: [:dvno])
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_for(bill) do |f| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="row">
  
 <div class="col-lg-6 col-md-6">
  <div class="control-group">
    <%= f.label :section, class: 'control-label' %>
    <div class="controls">

    <%= f.collection_select(:section, Section.all, :name, :name, 
    { prompt: 'Select a section' }, { id: 'section-select' }) %>

       
  </div>
  </div>
  </div>

<div class="col-lg-3 col-md-3">
  <div class="control-group">
  
    <%= f.label :year, class: 'control-label' %>
    <div class="controls">
     <%= f.select(:year, options_for_select([["2010","2010"],["2011","2011"],["2012","2012"],["2013","2013"],["2014","2014"],["2015","2015"],["2016","2016"],["2017","2017"],["2018","2018"],["2019","2019"],["2020","2020"],["2021","2021"],["2022","2022"],["2023","2023"],["2024","2024"],["2025","2025"]], :selected => f.object.year), :include_blank => true) %>
  </div>
</div>
</div>

<div class="col-lg-3 col-md-3">
  <div class="control-group">
  
    <%= f.label :month, class: 'control-label' %>
    <div class="controls">


     <%= f.select(:month, options_for_select([["JAN", "JAN"],["FEB", "FEB"],["MAR", "MAR"],["APR", "APR"],["MAY", "MAY"],["JUN", "JUN"],["JUL", "JUL"],["AUG", "AUG"],["SEP", "SEP"],["OCT", "OCT"],["NOV", "NOV"],["DEC", "DEC"]],  :selected => f.object.month), :include_blank => true) %>

  </div>
</div>
</div>
</div>
<br>


<div class="row">
  <div class="col-lg-6 col-md-6">
  <div class="control-group">
    <%= f.label :dvno, class: 'control-label' %>
    <div class="controls">
    <%= f.text_field :dvno, class: 'control-label' %>
  </div>
</div>
</div>


  <div class="col-lg-6 col-md-6">
  <div class="control-group">
    <%= f.label :Billtype, class: 'control-label' %>
    <div class="controls">

 <%= f.grouped_collection_select :typebill, Section.all, :typebills, 
    :name, :name, :name, { include_blank: 'Select a typebill' }, { id: 'typebill-select' } %>
  
   


   
  </div>
</div>
</div>
</div>
<br>

<div class="row">
  <div class="col-lg-6 col-md-6">
  <div class="control-group">
 
    <%= f.label :Rack, class: 'control-label' %>
    <div class="controls">
    <%= f.select(:compactor, options_for_select([["1","1"],["2","2"],["3", "3"],["4", "4"], ["5", "5"],["6", "6"],["7", "7"],["8", "8"],["9", "9"],["10", "10"],["11", "11"],["12", "12"],["13", "13"],["14", "14"],["15", "15"],["16", "16"],["17", "17"], ["18", "18"],["19", "19"],["20","20"], ["21", "21"]], :selected => f.object.compactor), :include_blank => true) %>
  </div>
</div>
</div>

 <div class="col-lg-6 col-md-6">
  <div class="control-group">
    <%= f.label :Shelf, class: 'control-label' %>
    <div class="controls">

    <%= f.collection_select(:rock, Rock.all, :name, :name, 
    { prompt: 'Select a Shelf' }, { id: 'rock-select' }) %>


   
  </div>
</div>
</div>
</div>
<br>

<div class="row">
  <div class="col-lg-6 col-md-6">
  <div class="control-group">
    <%= f.label :ShellAddress, class: 'control-label' %>
    <div class="controls">

    <%= f.grouped_collection_select :shelf, Rock.all, :shelves, 
    :name, :name, :name, { include_blank: 'Select a Shelf' }, { id: 'shelf-select' } %>


    
  </div>
</div>
</div>

  <div class="col-lg-6 col-md-6">
   <div class="control-group">
    <%= f.label :bundleno, class: 'control-label' %>
    <div class="controls">
    <%= f.text_field :bundleno, class: 'control-label' %>
  </div>
</div>

<!--
<% if can? :manage, User %>

  <div class="col-lg-6 col-md-6">
  <div class="control-group">
    <%= f.label :user_id, class: 'control-label' %>
    <div class="controls">
    <%= f.text_field :user_id, class: 'control-label' %>
  </div>
</div>
</div>
<% end %>
-->
</div>
</div>
<br>

  <div class="actions">
    <%= f.submit "StoreBill", class: 'btn btn-lg btn-warning center-block'%>
  </div>
<% end %>

app/views/bills/edit.html.erb
<div class="border-form-div">

<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<% if can? :manage, User %>
<%= link_to 'Show', @bill, class: 'btn btn-min btn-info' %>
 | <% end %>
<%= link_to 'Back', bills_path, class: 'btn btn-min btn-danger' %>

</div>

app/views/bills/index.html.erb
<div class="row">

<div class="col-lg-6 col-md-4">
Store A Single Bill? <br><span class="glyphicon glyphicon-hand-right blink_me" aria-hidden="true"></span>
 <span class="blink_me"><%= link_to 'Click Here',  new_bill_path, class: 'btn btn-lg btn-success' %> </span>
</div>


<div class="col-xs-6 col-md-4 pull-right">
 Retrieve A Bill? <br><span class="glyphicon glyphicon-hand-right blink_me" aria-hidden="true"></span>
 <span class="blink_me"><%= link_to 'Click Here',  new_search_path, class: 'btn btn-lg btn-warning' %> </span>


  
</div>

</div>
<div class="row">
<h1>Bills</h1>
</div>


<div class="row">

<h3>Store A Multi Bill?</h3>

<div class="col-lg-3 ">
<%= form_tag import_bills_path, multipart: true do %>

  <%= file_field_tag :file %>

 <br />


  <%= submit_tag "Import Bills", class: 'btn btn-md btn-danger' %>
<% end %>

</div>
</div>

<div class="media">
 
  <div class="media-body">
    <table class="table table-hover">  
  <thead>
    <tr>
      <th>Section</th>
      <th>Year</th>
      <th>Month</th>
    <th> Dvno</th>
      <th>Billtype</th>
      <th>Rack</th>
      <th>Shelf</th>
      <th>Shell Address</th>
      <th>Bundle No</th>
      <!--
      <th>User</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.section %></td>
        <td><%= bill.year %></td>
        <td><%= bill.month %></td>  
        <td><%= bill.dvno %></td>  
        <td><%= bill.typebill %></td>
        <td><%= bill.compactor %></td>
        <td><%= bill.rock %></td>
        <td><%= bill.shelf %></td>
        <td><%= bill.bundleno %></td>
        <!--
        <td><%= bill.user_id %></td> -->
        
        <td><%= link_to 'Show', bill, class: 'btn btn-sm btn-info' %></td>
        <% if can? :manage, User %>
        <td><%= link_to 'Edit', edit_bill_path(bill), class: 'btn btn-sm btn-success' %></td>
       <% end %>
       <!--
        <% if can? :manage, User %>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
     <% end %>
     -->
      </tr>
    <% end %>
    
  </tbody>
</table>
</div>

<br>
<div class="apple_pagination">
   
    <%= will_paginate @bills, :container => false %>
  </div>

</div>

app/views/bills/new.html.erb
<div class="border-form-div">

<h1>Input Screen</h1>



<%= render 'form', bill: @bill %>

<br />
<%= link_to 'Existing Bills', bills_path, class: 'btn btn-lg btn-info' %>
</div>

app/views/bills/show.html.erb
<div class="border-form-div">
<p>
  <strong>Section:</strong>
  <%= @bill.section %>
</p>


<p>
  <strong>Year:</strong>
  <%= @bill.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @bill.month %>
</p>


<p>
  <strong>DVNO:</strong>
  <%= @bill.dvno %>
</p>


<p>
  <strong>Billtype:</strong>
  <%= @bill.typebill %>
</p>

<p>
  <strong>Rack:</strong>
  <%= @bill.compactor %>
</p>

<p>
  <strong>Shelf:</strong>
  <%= @bill.rock %>
</p>

<p>
  <strong>Shell Address:</strong>
  <%= @bill.shelf %>
</p>

<p>
  <strong>BundleNo:</strong>
  <%= @bill.bundleno %>
</p>
<!--
<p>
  <strong>User:</strong>
  <%= @bill.user_id %>
</p>
-->
<% if can? :manage, User %>
<%= link_to 'Edit', edit_bill_path(@bill), class: 'btn btn-min btn-info' %> |
<% end %>
<%= link_to 'Back', bills_path, class: 'btn btn-min btn-danger' %>

</div>